spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true  
  datasource:
    url: jdbc:mysql://localhost:3306/nutritions_digital_assistant
    username: nda_root
    password: 123456789a
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    contexts: test,qa,main
